config/routes.rb
Rails.application.routes.draw do
  
  
    namespace :administrator do
    root :to => 'application#getdata'
    get 'application/getdata' =>'application#getdata'
    post 'application/showdata' =>'application#showdata'
    get 'application/sales'
    get 'application/order'
    get 'application/food'
    get 'application/customer'
    get 'application/extra'
    get 'application/index'
    end
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'




  get "sign_up" => "devise/registrations#new", :as => "sign_up"
  devise_for :members

  root :to => "store_details#index"
  resources :profiles
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  resources :products do
      resources :comments
  end
  
  resources :store_details do
    resources :addons
    resources :products do
    resources :comments
    post "make_pizza" => "products"
    delete "reset_topping" => "products"
  end
  end
  
  resources :products
  resource :cart, only: [:show]
  
  resources :order do 
   post "confirmed" => "carts"
   post "canceled" => "carts"
   get "payment_confirmation" => "carts"
  end
  
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  validates :comment, :rating, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
     @product = Product.find(params[:product_id])
     @store_detail = StoreDetail.find(@product.store_detail_id)
     puts("methods of index in food comments" ,@food.methods)
     @comments = @product.comments
    
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
     @product = Product.find(params[:product_id])
     @comment = @product.comments.find(params[:id])
    
  end

  # GET /comments/new
  def new
     @product = Product.find(params[:product_id])
     @comment = @product.comments.build
  end

  # GET /comments/1/edit
  def edit
     @product = Product.find(params[:product_id])
     @comment = @product.comments.find(params[:id])
    
  end

  # POST /comments
  # POST /comments.json
  def create
     @product = Product.find(params[:product_id])
     @comment = @product.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to product_comments_url, notice: 'Food comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
     @product = Product.find(params[:product_id])
     @comment = @product.comments.find(params[:id])
    
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to product_comment_url, notice: 'Food comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @product = Product.find(params[:product_id])
    @comment = @product.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to product_comments_url, notice: 'Food comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment, :rating)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@product, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', product_comment_path %> |
<%= link_to 'Back', product_comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment %></td>
        <td><%= comment.rating %></td>
        <td><%= link_to 'Show', product_comment_path(@product, comment) %></td>
        <td><%= link_to 'Edit', edit_product_comment_path(@product, comment) %></td>
        <td><%= link_to 'Destroy', product_comments_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_product_comment_path %>
<%= link_to 'Back to Pizza details', store_detail_product_path(@product, @store_detail) %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', product_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @comment.rating %>
</p>

<%= link_to 'Edit', edit_product_comment_path(@product, @comment) %> |
<%= link_to 'Back', product_comments_path %>