config/routes.rb
Rails.application.routes.draw do
  
  
    namespace :administrator do
    root :to => 'application#getdata'
    get 'application/getdata' =>'application#getdata'
    post 'application/showdata' =>'application#showdata'
    get 'application/sales'
    get 'application/order'
    get 'application/food'
    get 'application/customer'
    get 'application/extra'
    get 'application/index'
    end
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'




  get "sign_up" => "devise/registrations#new", :as => "sign_up"
  devise_for :members

  root :to => "store_details#index"
  resources :profiles
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  resources :products do
      resources :comments
  end
  
  resources :store_details do
    resources :addons
    resources :products do
    resources :comments
    post "make_pizza" => "products"
    delete "reset_topping" => "products"
  end
  end
  
  resources :products
  resource :cart, only: [:show]
  
  resources :order do 
   post "confirmed" => "carts"
   post "canceled" => "carts"
   get "payment_confirmation" => "carts"
  end
  
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :store_detail
  has_many :comments
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    
    @store_detail = StoreDetail.find(params[:store_detail_id])
    puts("methods are vvv" ,@store_detail.methods)
     @foods = @store_detail.foods
    
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
     @store_detail = StoreDetail.find(params[:store_detail_id])
     @food = @store_detail.foods.find(params[:id])
  end

  # GET /foods/new
  def new
    
   @store_detail = StoreDetail.find(params[:store_detail_id])
     
     @food = @store_detail.foods.build
  
  end

  # GET /foods/1/edit
  def edit
    @store_detail = StoreDetail.find(params[:store_detail_id])
    @food = @store_detail.foods.find(params[:id])
  end

  # POST /foods
  # POST /foods.json
  def create
    
    @store_detail = StoreDetail.find(params[:store_detail_id])
    @food = @store_detail.foods.build(params.require(:food).permit(:foodName, :foodType, :foodSize, :actualPrice, :offerPrice, :quantityAvailable, :hit))  
   #   @food = StoreDetail.find(params[:store_detail_id]).foodDetails.build(params.require(:food).permit(:foodName, :foodType, :foodSize, :actualPrice, :offerPrice, :quantityAvailable, :hit))  

    respond_to do |format|
      if @food.save
        format.html { redirect_to store_detail_foods_url, notice: 'Food detail was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
     @store_detail = StoreDetail.find(params[:store_detail_id])
 @food = Food.find(params[:id])
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to store_detail_food_url, notice: 'Food detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
     @store_detail = StoreDetail.find(params[:store_detail_id])
     @food = Food.find(params[:id])
     @food.destroy
    respond_to do |format|
      format.html { redirect_to store_detail_foods_path(@store_detail), notice: 'Food detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:foodName, :foodType, :foodSize, :actualPrice, :offerPrice, :quantityAvailable, :hit)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for([@store_detail, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :productName %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', store_detail_food_path %> |
<%= link_to 'Back', store_detail_foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<table>
  <thead>
    <tr>
      <th>Foodname</th>
      <th>Foodtype</th>
      <th>Foodsize</th>
      <th>Actualprice</th>
      <th>Offerprice</th>
      <th>Quantityavailable</th>
      <th>Hit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |food| %>
      <tr>
        <td><%= food.name %></td>
      <!--  <td><%= food.foodType %></td>
        <td><%= food.foodSize %></td>
        <td><%= food.actualPrice %></td>
        <td><%= food.offerPrice %></td>
        <td><%= food.quantityAvailable %></td>
        <td><%= food.hit %></td> -->
        <td><%= link_to 'Show', store_detail_product_path(@store_detail, product) %></td>
        <td><%= link_to 'Edit', edit_store_detail_product_path(@store_detail, product) %></td>
        <td><%= link_to 'Destroy', store_detail_products_path(@store_detail, product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_store_detail_product_path %>
<%= link_to 'Back to Store', @store_detail %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', store_detail_foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Foodname:</strong>
  <%= @food.name %>
</p>
<!..
<p>
  <strong>Foodtype:</strong>
  <%= @food.foodType %>
</p>

<p>
  <strong>Foodsize:</strong>
  <%= @food.foodSize %>
</p>

<p>
  <strong>Actualprice:</strong>
  <%= @food.actualPrice %>
</p>

<p>
  <strong>Offerprice:</strong>
  <%= @food.offerPrice %>
</p>

<p>
  <strong>Quantityavailable:</strong>
  <%= @food.quantityAvailable %>
</p>

<p>
  <strong>Hit:</strong>
  <%= @food.hit %>
</p>

<h2>Reviews</h2>
<% @product.comments.each do |comment| %>
<p>
  <strong>Comment:</strong>
  <%= comment.comment %>
</p>

<p>
  <strong>Rating:</strong>
  <%= comment.rating %>
</p>
<% end %>

<%= link_to 'Edit', edit_store_detail_product_path(@store_detail,@product) %> |
<%= link_to 'Back', store_detail_products_path(@store_detail) %> |
<%= link_to "Pizza Comments", product_comments_path(@product) %>