config/routes.rb
Rails.application.routes.draw do
  
  
    namespace :administrator do
    root :to => 'application#getdata'
    get 'application/getdata' =>'application#getdata'
    post 'application/showdata' =>'application#showdata'
    get 'application/sales'
    get 'application/order'
    get 'application/food'
    get 'application/customer'
    get 'application/extra'
    get 'application/index'
    end
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'




  get "sign_up" => "devise/registrations#new", :as => "sign_up"
  devise_for :members

  root :to => "store_details#index"
  resources :profiles
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  resources :products do
      resources :comments
  end
  
  resources :store_details do
    resources :addons
    resources :products do
    resources :comments
    post "make_pizza" => "products"
    delete "reset_topping" => "products"
  end
  end
  
  resources :products
  resource :cart, only: [:show]
  
  resources :order do 
   post "confirmed" => "carts"
   post "canceled" => "carts"
   get "payment_confirmation" => "carts"
  end
  
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/administrator/application_controller.rb
require 'graph'
require 'graph_decorator'

class Administrator::ApplicationController < ApplicationController
  
  def getdata
  end
  
  def showdata
     simpleGraph = BasicGraph.new(params[:chart])
     if params[:table] == 'dsales' then
      graphData = DSalesDecorator.new(simpleGraph)
     end
     if params[:table] == 'dsalesoffer' then
      graphData = DSaleOfferDecorator.new(simpleGraph)
     end
     if params[:table] == 'dsalestype' then
      graphData = DSaleTypeDecorator.new(simpleGraph)
     end
     if params[:table] == 'wsales' then
      graphData = WSalesDecorator.new(simpleGraph)
     end
     if params[:table] == 'wsalesoffer' then
      graphData = WSaleOfferDecorator.new(simpleGraph)
     end
     if params[:table] == 'wsalestype' then
      graphData = WSaleTypeDecorator.new(simpleGraph)
     end
     if params[:table] == 'msales' then
      graphData = MSalesDecorator.new(simpleGraph)
     end
     if params[:table] == 'msalesoffer' then
      graphData = MSaleOfferDecorator.new(simpleGraph)
     end
     if params[:table] == 'msalestype' then
      graphData = MSaleTypeDecorator.new(simpleGraph)
     end
     if params[:table] == 'pizza' then
      graphData = ProductDecorator.new(simpleGraph)
     end
     if params[:table] == 'hit' then
      graphData = ProductByHitDecorator.new(simpleGraph)
     end
     if params[:table] == 'customer' then
      graphData = ReturningCustomers.new(simpleGraph)
     end
     if params[:singleChart].to_s.length > 0 then
        @chart1 = graphData.singleChart
        puts "55555555555555555555555"
        puts @chart1.inspect
     end
     if params[:doubleChart].to_s.length > 0 then
        @chart2 = graphData.doubleChart
     end
     if params[:tripleChart].to_s.length > 0 then
        @chart3 = graphData.multipleChart
     end
  end

  def order
      y_name_1 = "Actual Price"
      y_name_2 = "Sold Price"
      chart_type = "spline"
      y_data_1 = Order.select("mrpPrice").group_by{|o| o.mrpPrice}.keys
      puts(y_data_1)
      y_data_2 = Order.select("soldPrice").group_by{|o| o.soldPrice}.keys
      puts(y_data_1)
      x_name = Order.select("orderId").group_by{|o| o.orderId}.keys
      y_data_3 = Order.select("offerGiven").group_by{|o| o.offerGiven}.keys
      y_name_3 = "Offer Given?"
      @chart3 = Charting.multichart(x_name, y_data_1, y_name_1, y_data_2, y_name_2, y_data_3, y_name_3, chart_type)
      @chart1 = Charting.singlechart(x_name, y_data_1, y_name_1, chart_type)
      @chart2 = Charting.doublechart(x_name, y_data_1, y_name_1, y_data_2, y_name_2, chart_type)
      #@chart4 = Charting.function_chart(x_name, y_data_1, y_name_1, y_data_2, y_name_2, chart_type)
  end
  
  def sales
      y_name_1 = "Non veg"
      y_name_2 = "Veg"
      chart_type = "pie"
      y_data_1 = DaySale.select("nonVeg").group_by{|o| o.nonVeg}.keys
      puts(y_data_1)
      y_data_2 = DaySale.select("veg").group_by{|o| o.veg}.keys
      puts(y_data_1)
      x_name = DaySale.select("id").group_by{|o| o.id}.keys
      y_data_3 = DaySale.select("totalSale").group_by{|o| o.totalSale}.keys
      y_name_3 = "Total sale"
      @chart3 = Charting.multichart(x_name, y_data_1, y_name_1, y_data_2, y_name_2, y_data_3, y_name_3, chart_type)
      @chart1 = Charting.singlechart(x_name, y_data_1, y_name_1, chart_type)
      @chart2 = Charting.doublechart(x_name, y_data_1, y_name_1, y_data_2, y_name_2, chart_type)
      #@chart4 = Charting.function_chart(x_name, y_data_1, y_name_1, y_data_2, y_name_2, chart_type)
  end
  
  def food
      y_name_1 = "Actual Price"
      y_name_2 = "Offer Price"
      chart_type = "bar"
      y_data_1 = Food.select("actualPrice").group_by{|o| o.actualPrice}.keys
      puts(y_data_1)
      y_data_2 = Food.select("offerPrice").group_by{|o| o.offerPrice}.keys
      puts(y_data_1)
      x_name = Food.select("foodName").group_by{|o| o.foodName}.keys
      y_data_3 = Food.select("quantityAvailable").group_by{|o| o.quantityAvailable}.keys
      y_name_3 = "Quantity Available"
      @chart3 = Charting.multichart(x_name, y_data_1, y_name_1, y_data_2, y_name_2, y_data_3, y_name_3, chart_type)
      @chart1 = Charting.singlechart(x_name, y_data_1, y_name_1, chart_type)
      @chart2 = Charting.doublechart(x_name, y_data_1, y_name_1, y_data_2, y_name_2, chart_type)
      #@chart4 = Charting.function_chart(x_name, y_data_1, y_name_1, y_data_2, y_name_2, chart_type)
  end
  
  def customer
      y_name_1 = "Actual Price"
      y_name_2 = "Offer Price"
      chart_type = "pie"
      y_data_1 = Food.select("actualPrice").group_by{|o| o.actualPrice}.keys
      puts(y_data_1)
      y_data_2 = Food.select("offerPrice").group_by{|o| o.offerPrice}.keys
      puts(y_data_1)
      x_name = Food.select("foodName").group_by{|o| o.foodName}.keys
      y_data_3 = [30,40,60]
      y_name_3 = "extra info"
      @chart3 = Charting.multichart(x_name, y_data_1, y_name_1, y_data_2, y_name_2, y_data_3, y_name_3, chart_type)
      @chart1 = Charting.singlechart(x_name, y_data_1, y_name_1, chart_type)
      @chart2 = Charting.doublechart(x_name, y_data_1, y_name_1, y_data_2, y_name_2, chart_type)
      #@chart4 = Charting.function_chart(x_name, y_data_1, y_name_1, y_data_2, y_name_2, chart_type)
  end
  
  def extra
      y_name_1 = "Actual Price"
      y_name_2 = "Offer Price"
      chart_type = "pie"
      y_data_1 = Food.select("actualPrice").group_by{|o| o.actualPrice}.keys
      puts(y_data_1)
      y_data_2 = Food.select("offerPrice").group_by{|o| o.offerPrice}.keys
      puts(y_data_1)
      x_name = Food.select("foodName").group_by{|o| o.foodName}.keys
      y_data_3 = [30,40,60]
      y_name_3 = "extra info"
      @chart3 = Charting.multichart(x_name, y_data_1, y_name_1, y_data_2, y_name_2, y_data_3, y_name_3, chart_type)
      @chart1 = Charting.singlechart(x_name, y_data_1, y_name_1, chart_type)
      @chart2 = Charting.doublechart(x_name, y_data_1, y_name_1, y_data_2, y_name_2, chart_type)
      #@chart4 = Charting.function_chart(x_name, y_data_1, y_name_1, y_data_2, y_name_2, chart_type)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  alias_method :current_user, :current_member
  include Pundit
  
  # Prevent CSRF attacks by raising an exception.
  #For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  #giving no authorisation to devise parameters
  #after_action :verify_authorized, unless: :devise_controller? 
  
  #to show better messages
  rescue_from Pundit::NotAuthorizedError, with: :member_not_authorized


  helper_method :current_order

  before_action :strict_transport_security
 
  def after_sign_in_path_for(resource)
  "/signedinuserprofile"
  end
    private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) do |member|
        member.permit(:email, :password, :password_confirmation, :first_name, :last_name)
      end

      devise_parameter_sanitizer.permit(:account_update) do |member|
        member.permit(:email, :password, :password_confirmation, :first_name, :last_name)
      end
    end
    
    def member_not_authorized
     respond_to do |format|
     format.html { redirect_to (root_path), notice: 'You have no access rights to view' }
     end
    end

    def current_order
      if !session[:order_id].nil?
       Order.find(session[:order_id])
       else
       Order.new
      end
    end
    
  def strict_transport_security
    if request.ssl?
      response.headers['Strict-Transport-Security'] = "max-age=31536000; includeSubDomains"
    end
  end
  

end

app/helpers/administrator/application_helper.rb
module Administrator::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/administrator/application/_form.html.erb
<li> <%= link_to "Admin Panel",rails_admin_path %></li> | 
<%= link_to "Order Graph",administrator_application_order_path %> | 
<%= link_to "Sales Graph",administrator_application_sales_path %> | 
<%= link_to "Customer Graph",administrator_application_customer_path %> | 
<%= link_to "Food Graph",administrator_application_food_path %> | 
<%= link_to "Extras",administrator_application_extra_path %>
<hr>
<h1>Charts</h1>
<%= high_chart("my_combine_div1", @chart1) %>
<%= high_chart("my_combine_div2", @chart2) %>
<%= high_chart("my_combine_div3", @chart3) %>
<%#= high_chart("my_combine_div4", @chart4) %>

app/views/administrator/application/customer.html.erb
<%= render 'form'%>

app/views/administrator/application/edit.html.erb
<h1>Editing Graph</h1>

<%= render 'form', graph: @graph %>

<%= link_to 'Show', @graph %> |
<%= link_to 'Back', graphs_path %>

app/views/administrator/application/extra.html.erb
<h1>Chart</h1>
<%= high_chart("my_combine_div", @chart) %>

app/views/administrator/application/food.html.erb
<%= render 'form'%>

app/views/administrator/application/getdata.html.erb
<li> <h1> <%= link_to "Go To Admin Dashboard >>>>>",rails_admin_path, class:"btn btn-primary btn-lg" %></h1></li> 
<hr>
<%= form_tag "administrator/application/showdata" do %>
  
  <div class="field">
    Choose your table
    <%= select_tag(:table, options_for_select([['Month Sales','msales'], ['Month Sales With Offers','msalesoffer'], ['Month Sales With Product Type','msalestype'], ['Pizza Pricing','pizza'], ['Pizza Ranking and Counts','hit'], ['Day Sales','dsales'], ['Day Sales With Offers','dsalesoffer'], ['Day Sales With Product Type','dsalestype'], ['Week Sales','wsales'], ['Week Sales With Offers','wsalesoffer'], ['Week Sales With Product Type','wsalestype'], ['Returning Customers','customer']])) %>
  </div>

  <div class="field">
    Choose the type of chart
    <%= select_tag(:chart, options_for_select([['Pie',"pie"], ['Spline',"spline"], ['Bar',"bar"], ['line',"line"]])) %>
  </div>

  <div class="field">
    Single Chart:
    <%= check_box_tag(:singleChart, "single chart") %>
  </div>
  <div class="field">
    Double Chart:
    <%= check_box_tag(:doubleChart, "double chart") %>
  </div>
  <div class="field">
    Triple chart:
    <%= check_box_tag(:tripleChart, "triple chart") %>
  </div>
  <div class="actions">
    <%= submit_tag 'view' %>
  </div>
<% end %>

app/views/administrator/application/new.html.erb
<h1>New Graph</h1>

<%= render 'form', administrator: @graph %>

<%= link_to 'Back', graphs_path %>

app/views/administrator/application/order.html.erb
<%= render 'form'%>

app/views/administrator/application/sales.html.erb
<%= render 'form'%>

app/views/administrator/application/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @graph.type %>
</p>

<p>
  <strong>Colum:</strong>
  <%= @graph.colum %>
</p>

<p>
  <strong>Table:</strong>
  <%= @graph.table %>
</p>

<%= link_to 'Edit', edit_graph_path(@graph) %> |
<%= link_to 'Back', graphs_path %>

app/views/administrator/application/showdata.html.erb
<li> <h1> <%= link_to "Go To Admin Dashboard >>>>",rails_admin_path, class:"btn btn-primary btn-lg" %></h1></li> 
<hr>
<%= form_tag do %>
  
  <div class="field">
    Choose your table
    <%= select_tag(:table, options_for_select([['Month Sales','msales'], ['Month Sales With Offers','msalesoffer'], ['Month Sales With Product Type','msalestype'], ['Pizza Pricing','pizza'], ['Pizza Ranking and Counts','hit'], ['Day Sales','dsales'], ['Day Sales With Offers','dsalesoffer'], ['Day Sales With Product Type','dsalestype'], ['Week Sales','wsales'], ['Week Sales With Offers','wsalesoffer'], ['Week Sales With Product Type','wsalestype'], ['Returning Customers','customer']])) %>
  </div>

  <div class="field">
    Choose the type of chart
    <%= select_tag(:chart, options_for_select([['Pie',"pie"], ['Spline',"spline"], ['Bar',"bar"], ['line',"line"]])) %>
  </div>

  <div class="field">
    Single Chart:
    <%= check_box_tag(:singleChart, "single chart") %>
  </div>
  <div class="field">
    Double Chart:
    <%= check_box_tag(:doubleChart, "double chart") %>
  </div>
  <div class="field">
    Triple chart:
    <%= check_box_tag(:tripleChart, "triple chart") %>
  </div>
  <div class="actions">
    <%= submit_tag 'view' %>
  </div>
<% end %>
<hr>
<h1>Hi der! Check out the Visualization</h1>
<% if @chart1 %>
<%= high_chart("my_combine_div1", @chart1) %>
<% end %>
<% if @chart2 %>
<%= high_chart("my_combine_div2", @chart2) %>
<% end %>
<% if @chart3 %>
<%= high_chart("my_combine_div3", @chart3) %>
<% end %>