config/routes.rb
Rails.application.routes.draw do
  
  
    namespace :administrator do
    root :to => 'application#getdata'
    get 'application/getdata' =>'application#getdata'
    post 'application/showdata' =>'application#showdata'
    get 'application/sales'
    get 'application/order'
    get 'application/food'
    get 'application/customer'
    get 'application/extra'
    get 'application/index'
    end
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'




  get "sign_up" => "devise/registrations#new", :as => "sign_up"
  devise_for :members

  root :to => "store_details#index"
  resources :profiles
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  resources :products do
      resources :comments
  end
  
  resources :store_details do
    resources :addons
    resources :products do
    resources :comments
    post "make_pizza" => "products"
    delete "reset_topping" => "products"
  end
  end
  
  resources :products
  resource :cart, only: [:show]
  
  resources :order do 
   post "confirmed" => "carts"
   post "canceled" => "carts"
   get "payment_confirmation" => "carts"
  end
  
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/addon.rb
class Addon < ApplicationRecord
  belongs_to :store_detail
  validates :addonName, presence: true
  validates :addonPrice, presence: true
end

app/models/click.rb
class Click < ApplicationRecord
  belongs_to :member
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  validates :comment, :rating, presence: true
end

app/models/dsale.rb
class Dsale < ApplicationRecord
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :store_detail
  has_many :comments
end

app/models/medical.rb
class Medical < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :established_stores,class_name:"StoreDetail",dependent: :destroy
  has_one :profile,dependent: :destroy
  has_many :clicks

  # Include default devise modules. Others available are:
  # :confirmable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable,:timeoutable,password_length: 9..128
         
   validate :strong_password_check
   validates :email, uniqueness: true, presence: true
   #validates :user_name, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z]+([a-zA-Z]|\d)*\Z/ }

  def strong_password_check
    if password.present? and not password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)./)
    errors.add :password, "must include at least one lowercase letter, one uppercase letter, and one digit"
    end
  end
end

app/models/member_observer.rb
require 'pizza_app_logger'

class MemberObserver < ActiveRecord::Observer
  def after_create(member)
     logger = MyLogger.instance
     logger.logInformation(member.email)    
      MemberMailer.welcome_member_email(member).deliver!
  end
end

app/models/msale.rb
class Msale < ApplicationRecord
end

app/models/order.rb
require 'observer'

class Order < ApplicationRecord
  include Observable

  belongs_to :order_status
  has_many :order_items

  before_save :total_cart_price
  
  after_save :add_notifier
  #include OrderObserver
  
  

  def totalcartprice
    order_items.collect { |orderitem| orderitem.valid? ? (orderitem.quantity * orderitem.unit_price) : 0 }.sum
  end
  

  
  def total_cart_price
    self[:subtotal] = totalcartprice
  end
private

  def add_notifier
    add_observer(OrderObserver.new)
    changed
    notify_observers(self)
       puts("yyyyyyyyyy")
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  #validates :total_price, :unit_price, presence: true
  validate :any_product_present
  validate :any_order_present
  
  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def any_product_present
    if product.nil?
      errors.add :product,"is not valid or is not active.Sorry for the inconvience caused"
    end
  end

  def any_order_present
    if order.nil?
      errors.add :order, "is not a valid order.Sorry for the inconvience caused"
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_observer.rb
require 'product_update_single'
require 'pricing_observer'
class OrderObserver
  def update(record)
    if record.order_status.name == "Confirmed"
      puts("***********************qwerrty")
       MemberMailer.order_email(record).deliver
     	record.order_items.each do |order_item|
         order_item.product.update_attribute(:quantityAvailable,order_item.product.quantityAvailable.to_i - order_item.quantity) 
        end

      product_count_update
      #price_change
    end
  end
  
  def product_count_update
    @product_count = ProductUpdateSingleton.instance
    @count_up = @product_count.count_update
    puts(@count_up)
  end
  
  def product_refresh_qty
    @refresh = ProductUpdateSingleton.instance
    @refresh_qty = @refresh.refresh_quantity
    puts(@refresh_qty)
  end
  
  def price_change
    order = OrderSend.new()
    result = Pricing.new(order)
    puts(result)
    order.notify_observers
    puts("Pricing is completed. =========================================== Now count update and hit update is going to perform")
  end
  
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	  has_many :orders,dependent: :destroy
	  validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :store_detail
  has_many :comments,dependent: :destroy
  validates :name, :quantityAvailable, :allergens, :description, presence: true
  validates :price, :active, :foodType, :foodSize, :calorie, presence: true
  validates :offerPrice, presence: true

  serialize :tapping
  default_scope { where(active: true) }
  def self.policy_class
      ProductPolicy
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :member
  attr_accessor :firstName, :lastName, :building, :street, :city, :pincode, :mobile, :dateOfBirth, :email, :idProof
  validates :firstName, :lastName, :building, :street, :city, :pincode, :dateOfBirth, :email, presence: true
  validates :idProof, uniqueness: true, presence: true
  validates :mobile, uniqueness: true, presence: true
   
end

app/models/store_detail.rb
class StoreDetail < ApplicationRecord
    belongs_to :member, class_name: "Member", foreign_key: "member_id"
    has_many :products,dependent: :destroy
    has_many :addons,dependent: :destroy
    attr_accessor :store_name, :building, :street, :city, :pincode, :store_mobile, :store_email
    validates :store_name, :building, :street, :city, :pincode, :store_mobile, :store_email, presence: true

   def self.policy_class
      StoreDetailPolicy
   end
end

app/models/wsale.rb
class Wsale < ApplicationRecord
end

app/helpers/addons_helper.rb
module AddonsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/graph/getdata.html.erb
<%= form_tag "/graph/showdata" do %>
  
  <div class="field">
    Choose your table
    <%= select_tag(:table, options_for_select([['Order Table','order'], ['Food Table','food'], ['Sales Table','sales'], ['Returning Customers','customer count']])) %>
  </div>

  <div class="field">
    Choose the type of chart
    <%= select_tag(:chart, options_for_select([['Pie',"pie"], ['Spline',"spline"], ['Bar',"bar"], ['line',"line"]])) %>
  </div>

  <div class="field">
    Single Chart:
    <%= check_box_tag(:singleChart, "single chart") %>
  </div>
  <div class="field">
    Double Chart:
    <%= check_box_tag(:doubleChart, "double chart") %>
  </div>
  <div class="field">
    Triple chart:
    <%= check_box_tag(:tripleChart, "triple chart") %>
  </div>
  <div class="field">
    Combo chart:
    <%= check_box_tag(:multiChart, "multiple chart") %>
  </div>

  <div class="actions">
    <%= submit_tag 'view' %>
  </div>
<% end %>

app/views/graph/showdata.html.erb
<%= form_tag '/graph/showdata' do %>
  
  <div class="field">
    Choose your table
    <%= select_tag(:table, options_for_select([['Order Table','order'], ['Food Table','food'], ['Sales Table','sales'], ['Returning Customers','customer count']])) %>
  </div>

  <div class="field">
    Choose the type of chart
    <%= select_tag(:chart, options_for_select([['Pie','pie'], ['Spline','spline'], ['Bar','bar'], ['line','line']])) %>
  </div>

  <div class="field">
    Single Chart:
    <%= check_box_tag(:singleChart, "single chart") %>
  </div>
  <div class="field">
    Double Chart:
    <%= check_box_tag(:doubleChart, "double chart") %>
  </div>
  <div class="field">
    Triple chart:
    <%= check_box_tag(:tripleChart, "triple chart") %>
  </div>
  <div class="field">
    Combo chart:
    <%= check_box_tag(:multiChart, "multiple chart") %>
  </div>

  <div class="actions">
    <%= submit_tag 'view' %>
  </div>
<% end %>

<hr>

<h1>Hi der! Visualization</h1>
<%= high_chart("my_combine_div1", @chart1) %>
<%= high_chart("my_combine_div2", @chart2) %>
<%= high_chart("my_combine_div3", @chart3) %>
<%= high_chart("my_combine_div4", @chart4) %>

app/views/layouts/_cart_text.html.erb
<% if current_order.order_status_id == 2 or current_order.order_items.size==0%>
<%= link_to " CART[0]", cart_path, class: "btn btn-info" %>
  <% else %>
<%= link_to " CART[#{current_order.order_items.size}] ( #{number_to_currency(current_order.subtotal,unit: "£")} )", cart_path, class: "btn btn-info" %>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dublin Pizza Shops</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %>
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
<style>
body {margin: 0;}

ul.topnav {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
    text-align: center;
}

ul.topnav li {float: left;}

ul.topnav li a {
    display:inline-block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

ul.topnav li a:hover:not(.active) {background-color: #111;}

ul.topnav li a.active {background-color: #4CAF50;   display:inline-block;
    float: none;  text-align: center; }

ul.topnav li.right {float: right;}

@media screen and (max-width: 600px){
    ul.topnav li.right, 
    ul.topnav li {float: none;}
}
body {
    background-color: lightblue;
}
</style>
  </head>
    <ul class="topnav">
        <tr>
         <li class="active"><%= link_to "Home", root_path %></li>
           <% if member_signed_in? %>
          <li class="active"><%= link_to "Profile", signedinuserprofile_path %></li>
           <%end%>
        <% unless member_signed_in? %>
          <li class="right"><%= link_to "Sign up", new_member_registration_path %></li>
          <li class="right"><%= link_to "Log in", new_member_session_path %></li> 
        <% end %>
         <% if member_signed_in? && current_member.admin? %>
             <li><%= link_to "Admin Panel",administrator_root_path %><li>
         <%end%>
         </tr>
         <tr>
         <li class="right">
         <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
         </li>
         </tr>
         <tr>
         <%if member_signed_in? %>
          <li class="right"><%= link_to "Log out", destroy_member_session_path, method: :delete %></li>
          <li class="right"><%= link_to current_member.email,edit_member_registration_path %><li>
         <% end %>
         </tr>

  </ul>
  <div class="container-fluid">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p
    <%= yield %>
  </div>
    
  </body>
</html>